theme = "tokyonight"

[editor]
bufferline = "multiple"
true-color = true
line-number = "relative"
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-save = true
auto-format = true
color-modes = true
 
[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

