vim.keymap.set("n", "<leader>gg", [[:tab Git<cr>]])
vim.keymap.set("n", "<leader>gd", [[:tab Git diff<cr>]])
vim.keymap.set("n", "<leader>gc", [[:tab Git commit<cr>]])
vim.keymap.set("n", "<leader>gz", vim.cmd.Gread)
--vim.keymap.set("n", "<leader>gw", vim.cmd.Gwrite)
vim.keymap.set("n", "<leader>gX", [[:GRemove<cr>]])

vim.keymap.set("n", "<leader>gp", function()
  local input = vim.fn.input('git push ')
  vim.cmd('Git push ' .. input)
end)
vim.keymap.set("n", "<leader>gu", function()
  local input = vim.fn.input('git pull ')
  vim.cmd('Git pull ' .. input)
end)
vim.keymap.set('n', '<leader>gb', function()
  local input = vim.fn.input('git branch ')
  vim.cmd('Git branch ' .. input)
end)
vim.keymap.set('n', '<leader>gs', function()
  local input = vim.fn.input('git switch ')
  vim.cmd('Git switch ' .. input)
end)
