local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>ft", mark.toggle_file)
vim.keymap.set("n", "<leader>fc", mark.clear_all)
vim.keymap.set("n", "<leader>ff", ui.toggle_quick_menu)

vim.keymap.set("n", "<leader>fi", function() ui.nav_file(1) end)
vim.keymap.set("n", "<leader>fu", function() ui.nav_file(2) end)
vim.keymap.set("n", "<leader>fe", function() ui.nav_file(3) end)
vim.keymap.set("n", "<leader>fo", function() ui.nav_file(4) end)
vim.keymap.set("n", "<leader>fa", function() ui.nav_file(5) end)
vim.keymap.set("n", "<leader>fx", function() ui.nav_file(6) end)
vim.keymap.set("n", "<leader>fk", function() ui.nav_file(7) end)
vim.keymap.set("n", "<leader>fj", function() ui.nav_file(8) end)
vim.keymap.set("n", "<leader>fq", function() ui.nav_file(9) end)
vim.keymap.set("n", "<leader>f;", function() ui.nav_file(10) end)
