require("persistence").setup()

vim.keymap.set("n", "<leader>qq", function()
  require("persistence").load()
end, {})
vim.keymap.set("n", "<leader>qx", function()
  require("persistence").stop()
end, {})
vim.keymap.set('n', '<leader>ql', function()
  require('persistence').list()
end, {})
vim.keymap.set('n', '<leader>qs', function()
  require('persistence').save()
end, {})
