[build]
rustc-wrapper = "/home/jonsson-nils/.nix-profile/bin/sccache"

[target.x86_64-unknown-linux-gnu] 
linker = "clang" 
rustflags = ["-C", "link-arg=-fuse-ld=/home/jonsson-nils/.nix-profile/bin/mold"]

